services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_NAME:-tcc}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - '${DB_PORT:-5432}:5432'
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
